# 公共配置文件

spring:
  application:
    name:
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aibi
    username: root
    password: fujia
  # Redis 配置
  redis:
    database: 8
    host: localhost
    port: 6379
    password: fujia
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  #开启失败后重试机制，重试两次
  rabbitmq:
    host: localhost
    port: 5672
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 500ms
          multiplier: 2
          max-attempts: 2
          stateless: true
server:
  address: 0.0.0.0
  port: 8081
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 对象存储
# todo 需替换配置
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.aibi.springbootinit.controller
#Ai接口配置
xunfei:
  client:
    appid: f66e3482
    apiSecret: YjQ0YmNjMzdlZjczNDE2ZTE2YTEwNDEz
    apiKey: 40ca34f457b1da0eeb6253d1c506b6aa